### ISSUE TITLE
High-latency connection repeatedly failing with 'bad record mac'

### ISSUE THREAD

**Issue by bmhatfield** [ruby-amqp/bunny#289]
Hi,

I have a client that I recently upgraded to Bunny `1.7.0` (alongside a coordinated upgrade to RabbitMQ `3.5.0` and Erlang ESL `1:16.b.3-2`) with the intent of enabling RabbitMQ TLS to support clients in a new AWS region.

I had previously been using Bunny `1.1.8` for a little over a year over plain TCP with low latency with no problems.

The new AWS region sees a very consistent, very stable 232ms connection to the existing one:

```
--- old-region-to-new-region ping statistics ---
239 packets transmitted, 239 received, 0% packet loss, time 238301ms
rtt min/avg/max/mdev = 230.020/231.957/235.214/1.406 ms
```

For a little while, I ran this connection over plain TCP with Bunny `1.1.8`, and I observed the behavior as stable.

Unfortunately, since upgrading and TLS, I am seeing this error:

`W, [2015-04-01T14:52:45.998258 #2852]  WARN -- #<Bunny::Session:34501320 RABBIT-USER@THE-RABBIT-SERVER:5671, vhost=/, hosts=[THE-RABBIT-SERVER]>: Recovering from a network failure...`

No other errors or information is logged, and evidence of a successful reconnection is not observed (ie, no further events are received).

On the RabbitMQ side, I see this error repeatedly:

```
accepting AMQP connection <0.26773.6> (CLIENT:36915 -> SERVER:5671)
--
closing AMQP connection <0.26773.6> (CLIENT:36915 -> SERVER:5671):
connection_closed_abruptly
--
accepting AMQP connection <0.26850.6> (CLIENT:37008 -> SERVER:5671)
--
closing AMQP connection <0.26850.6> (CLIENT:37008 -> SERVER:5671):
{inet_error,{tls_alert,"bad record mac"}}
--
accepting AMQP connection <0.28201.6> (CLIENT:38449 -> SERVER:5671)
--
closing AMQP connection <0.28201.6> (CLIENT:38449 -> SERVER:5671):
{inet_error,{tls_alert,"bad record mac"}}
--
accepting AMQP connection <0.31956.6> (CLIENT:39416 -> SERVER:5671)
--
closing AMQP connection <0.31956.6> (CLIENT:39416 -> SERVER:5671):
{inet_error,{tls_alert,"bad record mac"}}
```

The CLIENT and SERVER is the same each time.

I have observed that the interval between the `accepting` and `closing` messages are about 10m each time - roughly consistent with the 580s heartbeat in RabbitMQ (which was a default, or I set it a very long time ago and forgot).

How can I proceed with troubleshooting this?

Thank you!
Brian

**Comment by michaelklishin** [comment]
```
{inet_error,{tls_alert,"bad record mac"}}
```

is why RabbitMQ closes connection. You can make heartbeat timeout much lower, e.g. 15 seconds, and follow [TLS troubleshooting](http://www.rabbitmq.com/troubleshooting-ssl.html) steps.

I also suspect that heartbeat-driven timeouts may not be starting recovery process. But "bad record mac" is the root cause.

**Comment by michaelklishin** [comment]
I'd be happy to investigate the missed heartbeats reconnection case but it requires either having the server in a VM with iptables rules that drop outgoing traffic or RabbitMQ server modifications that make heartbeat "sender"/timer a no-op. And I likely won't have much time for that in the upcoming month or two.

Fixing the root cause with networking should make the issue largely irrelevant for you.

**Comment by bmhatfield** [comment]
Hi,

Thanks for your (very fast) response. You closed this issue, but all of my research seems to indicate that 'bad record mac' basically means a client or network issue of some form, such that the message fails. It doesn't really give me a lot to go on to resolve this. Neither the string "mac" nor "bad" appear on the linked troubleshooting page, nor is there any conceptual information about periodic connection drops.

I'm not sure what the root cause with networking you're referring to is - the connection is very stable (see the ping output in the filed issue), it's just got a high latency. I cannot fix that, because the machines are physically very far away from each other (singapore, and the east coast of the united states, to be specific.)

Would it be possible to suggest tunables or other places to start this investigation?

Thanks,
Brian

**Comment by michaelklishin** [comment]
I close all issues that are questions.

"Bad record MAC" can mean:

 * Malformed/"bad" packets
 * Public/private key mismatch
 * Buggy TLS implementation on either end

and more. It means that Erlang's TLS implementation cannot be sure about the integrity of data it's received.

I'm sorry but stable ping is by no means an indication of a "stable TCP connection". Ping uses ICMP. Bunny does not. `ping` will not help you detect bogus routers and switches that may send malformed packets every so often.

You can try Erlang 17.4, we don't hear about TLS edge cases with 17.x. You could try moving your app to another machine/layer 2 link if that's an option. You can run "regular" connections under stunnel to see if it makes a difference. You can try another client (e.g. the Java one) to see if the issue can be reproduced.

Searches for the "bad record mac" TLS alert reveal all kinds of obscure issues. You haven't previously been having them because you were not using TLS: what makes you believe Bunny 1.7 is the primary offender?

**Comment by michaelklishin** [comment]
I've mentioned earlier that "bad record mac" could indicate public/private key mismatch. That's not true: TLS uses symmetric encryption for application data after asymmetric encryption has been used for authentication and session key transfer.

**Comment by michaelklishin** [comment]
TLS troubleshooting guide covers what accounts for maybe 95% of all issues we see: they are issues with key and certificate setup, incorrectly used ports, hostname mismatch for certificates, etc.

rabbitmq.com is not a site about TLS in general, so we do not cover all TLS alerts. Yes, the word "MAC" does not appear there. The line "bad record mac" reveals plenty of Google search results, for any TLS implementation (Erlang or not), including OpenSSL documentation for the alert.

**Comment by michaelklishin** [comment]
Heartbeats (those "periodic disconnects") have a [documentation guide](http://www.rabbitmq.com/heartbeats.html) that explains why they exist.

**Comment by bmhatfield** [comment]
@michaelklishin FWIW, I figured this out - it ended up being concurrent access to the socket file descriptor due to a forked child process causing the MAC calculations to be wrong.

**Comment by michaelklishin** [comment]
thank you, I will add this to Bunny and RabbitMQ guides as an example.

**Comment by bmhatfield** [comment]
Wow! I just noticed this is already in the RabbitMQ docs. Thanks again for your help here.
