### ISSUE TITLE
Consumers subscribed to a queue become quietly unsubscribed after their node promotes to master

### ISSUE THREAD

**Issue by svdasein** [ruby-amqp/bunny#295]
In an HA failover situation where a node which had been a slave gets promoted to master, clients subscribed to a synch'd queue on that server seem to quietly cease being consumers of the queue they'd subscribed to.  afaict there's no exception raised when this  happens - the client sits there connected and waiting for data from its subscription which is in fact not valid according to the server.

I have tried permutations w/ heartbeat and automatic connection recovery to no avail.  Am I doing something wrong or is this a real issue?

**Comment by michaelklishin** [comment]
Can you provide exact steps to reproduce? If this is an issue, then it's not with Bunny for sure.

**Comment by svdasein** [comment]
I used these guides:

https://www.rabbitmq.com/clustering.html
Pretty much there you just follow the instructions to get two nodes working together

Then you set up an synchronized HA queue
https://www.rabbitmq.com/ha.html

I used this queue policy:

ha-mode:	all
ha-sync-mode:	automatic

Given that setup, write a client that subscribes to the queue.  Once they're connected and working, keep browse to the page that shows queue subscribers for that queue.  You should see consumers from both machines.  Now shut down whichever node is the master in the rabbitmq cluster.   You'll note that all consumers go away and do not come back.  If you then restart the node you shut down, you'll see the consumers come back (assuming you did auto-reconnect).  However, the clients that are connected to the node that got transitioned to master remain absent.

If you need more specifics let me know.

**Comment by svdasein** [comment]
"Correct" behavior would at least have some sort of signal from the server that the subscription got cancelled right?

**Comment by michaelklishin** [comment]
See [Consumer Cancellation and Failover](https://www.rabbitmq.com/consumer-cancel.html).

**Comment by svdasein** [comment]
Michael - fixed with subscribe_with & consumer w/ cancellation handler - thanks for your time.

**Comment by svdasein** [comment]
Michael - sorry - this isn't an "issue" per se but I could use a nudge in the right direction if you have a moment:

It looks like subscribe_with does not yield to a block like subscribe does,  In consumer_cancellation_notification.rb I get how to set up to catch the cancellation, but it's not clear to me where the logic that would go in the block passed to subscribe would  go.  I did find something here http://rubybunny.info/articles/queues.html that makes it look like I have to really restructure a lot of stuff.

Could you describe the migration from passing a block into subscribe() to using subscribe_with()?

Or maybe alternatively - is there a way I can catch cancellations without using the subscribe_with() call model?

Thanks - I appreciate your taking time on what are pretty obviously "dumb newb" questions.

**Comment by michaelklishin** [comment]
I'm sorry but we do not use issues for questions.

**Comment by michaelklishin** [comment]
If you take a look at the [Consumer instances](http://rubybunny.info/articles/queues.html#consumer_instances) section, it mentions that it accepts a consumer object.

`Bunny::Queue#subscribe` [creates a consumer object](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/queue.rb#L183-193) that only implements one or two methods. You can pass it a callable as `:on_cancellation` which will be used to implement `Bunny::Consumer#handle_cancellation`. Because we don't want to pass 5 options that are callables, at some point `Bunny::Consumer` was introduced (it is also easy to reason about during recovery, unlike 5 arbitrary functions).

You can provide any `Bunny::Consumer` [subclass](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/consumer.rb) to `Bunny::Queue#subscribe_with`. The entire consumer API is about 5 functions. It should not be too hard to figure out which is invoked when.
