### ISSUE TITLE
Consumer cancelation sometimes does not break out of subscribe loop

### ISSUE THREAD

**Issue by mprostko** [ruby-amqp/bunny#322]
I'm having a problem with the queue subscribe loop. I'm using bunny as a communication between two ruby scripts - client and consumer. Consumer is a worker that listens for requests, then sends out replies (in this example, 3 "noop" messages, and a "ok" message that ends the communication) to the requesting client. The client is listening for those messages and when the "ok" message arrives it should end the subscribe loop and close itself.
The problem that I am having is that the
```ruby
delivery_info.consumer.cancel
```
does not exit the subscribe loop every time. It works few times and then randomly doesnt jump out from the loop. The code after that cancelation is executed (error message) and it looks like the code is at the beginning of the subscribe loop again, waiting for another message. The number of successfuly closed  clients is random.

How am I supposed to break out of that loop safely, and be sure that it is cancelled properly?

I hope that you can reproduce the error with these gists:
Consumer: https://gist.github.com/mprostko/6556df986a50b9e624bb
Client: https://gist.github.com/mprostko/2c96323367d1365c18b4
Log: https://gist.github.com/mprostko/0a5a0e76dde8e2131b19

**Comment by michaelklishin** [comment]
Please use mailing list for questions.

Your consumer code does not cancel the consumer anywhere, just unbinds the queue.

**Comment by mprostko** [comment]
How come should Consumer cancel the Client? The idea was that the Client would **cancel itself** when he receives an ending message. But by doing so the cancellation behaviour is undefined - this is why I'm creating this as a issue here, not a question. If you mind explaining me why the code after the cancellation is executed when as far as I understand it, it shouldn't be executed.

**Comment by michaelklishin** [comment]
OK, so you have two code files and I haven't noticed the other one.

The `:block` option is not meant to be used with self-cancelling consumers. Drop it if you plan on using one. It only exists for the most basic use case: "block this thread because I want to be consuming
forever, and not sure how to do this properly in Ruby".

When you cancel a consumer, `Bunny::Channel#basic_cancel` first sends a `basic.consume` frame and waits for server response, only then it will consider shutting down consumer thread pool, which unblocks the caller. Now that Bunny no longer supports Ruby 1.8 and 1.9, there *may* be a better way to implement this but right now that's how it works.

Also, there is inherently a race condition between `basic.cancel` and messages that are in flight to your consumer. Those need to be handled somehow. Some clients have a graceful shutdown period: process whatever comes in or is already being processed for N seconds, then shut down completely. Bunny will drop those messages on the floor with a warning that there's no consumer to handle them.

There are rarely reasons to use the `:block` option. If you want to wait (block a thread) until a certain event happens, use a countdown latch-like primitive (of which Ruby doesn't have many) — see `Bunny::Concurrent` and `ActiveSupport::Concurrent` — in your own code. This way you have full control about how things work.
