### ISSUE TITLE
non-English symbols in message

### ISSUE THREAD

**Issue by DmitryDrobotov** [ruby-amqp/bunny#391]
Hi guys!

When I am trying to publish message with non-English symbols (like `Offre illimitée mensuelle`) it does not appear anywhere (rabbitmq shows that 0 messages in the queue and no one consumer received this message). Looks like rabbitmq rejects it but no information was found in logs and no exceptions raised in the app. It is fully silent.

Example:
```
connection = Bunny.new(...)
connection.start
channel = connection.create_channel
channel.default_exchange.publish('Offre illimitée mensuelle', routing_key: 'my.queue.name', headers: { my_custom_header: 1, my_another_customer_header: 2 })
```

```
MRI 2.3.0
Bunny 2.3.0
RabbitMQ 3.6.1
Erlang 18.2
```

Please, recommend me how can I resolve this problem. Thanks a lot!

**Comment by michaelklishin** [comment]
RabbitMQ does not care what's in message payload and neither does Bunny. Please post questions to the mailing list and post a complete code snippet and RabbitMQ logs.

**Comment by michaelklishin** [comment]
If the above snippet is what you actually run, it's the same issue as in https://github.com/ruby-amqp/bunny/issues/350 and the answer is: [use publisher confirms](http://www.rabbitmq.com/confirms.html) and properly close connection before the script exits, otherwise even with socket lingering you don't get any guarantees that your data is sent, leave alone actually received, before the VM terminates.
