### ISSUE TITLE
Priorities doesn't work as behavior

### ISSUE THREAD

**Issue by sveredyuk** [ruby-amqp/bunny#396]
Hi all. I found some issues when tryu to use priorities in bunny. Found at StackOverflow same [issue](http://stackoverflow.com/questions/29304827/how-to-publish-messages-with-priority-using-bunny-gem-to-rabbitmq)  Any comment ?

And also i found strange thing. When consumer just subscribed at queue with prioritized messages it works well and take message with highest priorities first, but for new messages published to the same queue it ignore priority (i used sleep pause.. it doesn't help)

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

We cannot suggest much from "when I try to use priorities". Please be more specific about what you try to do and what you expect.

**Comment by michaelklishin** [comment]
If you use the priority queue feature then it has [limitations that have been documented for a long time](http://www.rabbitmq.com/priority.html), in particular that if a message goes directly to a consumer and is not stored in the message store then it is not prioritised (RabbitMQ would have to delay deliveries in order to do so, which few people would agree to).

**Comment by sveredyuk** [comment]
Thx a lot for answer. I will continue to seek decision.
