### ISSUE TITLE
Recovery attempts limit is effectively ignored

### ISSUE THREAD

**Issue by camelpunch** [ruby-amqp/bunny#408]
Something interesting seems to be happening with recovery. There's a [line that decrements attempts](https://github.com/ruby-amqp/bunny/blob/e5d8cb36447fa36bc7a7e353cfe62f8861564465/lib/bunny/session.rb#L692) but no accompanying reset. However, channel operations seem to recover on their own even when the number of attempts is set low.

Not a huge deal, but thought I'd record this thought before forgetting it.

**Comment by michaelklishin** [comment]
I did some poking around and think that the author (seems to be @jafrog in fff7f4465d2261e8bfbb840d9012c8a13edb9929) intended it to work like this: the counter is global for the entire lifetime of a connection object.

I agree that this may be counterintuitive to most and decided to change it. One issue with
the per-recovery attempt limit is that Bunny tests that use HTTP client to force close connections
cannot simulate counted retries (TCP failures) easily since the server is up and thus any reconnection will succeed and reset the counter. I don't have a solution that's not environment-specific or fragile (e.g. stopping RabbitMQ and trying to start ti back), so leaning towards deleting the test after a lot of manual testing \_(ツ)_/¯.

**Comment by lockyluchiano** [comment]
1
