### ISSUE TITLE
Support for TLS SNI

### ISSUE THREAD

**Issue by c-knowles** [ruby-amqp/bunny#440]
The compose.io implementation of RabbitMQ needs SNI on the TLS connection in order to verify correctly, at least on their very latest implementation. I was looking through the bunny docs and code but didn't spot any support for it. Is there any? If not I may submit the change for review.

The openssl equivalent would be along the lines of adding `servername`:
`openssl s_client -connect HOST:PORT -servername HOST`

It's [undocumented](https://github.com/ruby/openssl/issues/81) but Ruby seems to support this via `hostname` on the SSL socket:

``` ruby
socket = OpenSSL::SSL::SSLSocket.new(tcp_client, ssl_context)
socket.hostname = 'HOST'
socket.connect
```

**Comment by michaelklishin** [comment]
@c-knowles thanks. Do you know what's the earliest Ruby version to provide `OpenSSL::SSL::SSLSocket#hostname`?

**Comment by michaelklishin** [comment]
Three Bunny classes that are relevant if you are to consider a PR:

 * [Bunny::Transport](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/transport.rb#L359)
 * [Bunny::Socket](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/cruby/ssl_socket.rb) for MRI
 * [Bunny::Socket](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/cruby/ssl_socket.rb) for JRuby (JRuby support for Bunny is a "best effort" kind of feature since there's a dedicated JRuby client, March Hare)

Thank you.

**Comment by c-knowles** [comment]
Not sure about the versions yet, I do know it seems to have been in there since at least 2015. So if there is no support yet or planned I will likely have a go at a pull request soon, doesn't look like the changes would be that big.

**Comment by michaelklishin** [comment]
We can always set that field only if the socket object responds to `:hostname`.

**Comment by c-knowles** [comment]
According to https://github.com/ruby/openssl/issues/81 on the `hostname` setting:
```
Yes, it is part of the public API, since Ruby 1.9.2 (note it requires OpenSSL >= 0.9.8f).

RDoc comment was fixed some time ago, and OpenSSL::SSL::SSLSocket#hostname= 
now shows up in the latest HTML generated from the master branch:

http://ruby.github.io/openssl/OpenSSL/SSL/SSLSocket.html#method-i-hostname-3D
```

**Comment by lockyluchiano** [comment]
1
