### ISSUE TITLE
undefined method `message_count'

### ISSUE THREAD

**Issue by olegsobchuk** [ruby-amqp/bunny#460]
I use `Bunny` (RabbitMQ) for delivery data via queue and `Sidekiq` for process some actions with data.
So when I run application for processing about 300 messages I get next error

`NoMethodError: undefined method `message_count' for #<AMQ::Protocol::Exchange::DeclareOk:0x00000005142558>`

I figured out that it happens when beckground job after processing try `publish` data to next queue. This job fall down and moves to retry jobs. But after retry (maybe couple retries) that jobs finishes without errors. 

From about 300 messages I can get about 60 retries with that error.

I tried decrease concurrency pool size in Sidekiq from 20 to 5, but this didn't change situation.

**Comment by michaelklishin** [comment]
See #386. Pretty much every time this comes down to a channel being shared between threads to do publishing or operations that expect a server response (e.g. `queue.declare`). That's [not a safe thing to do](http://rubybunny.info/articles/concurrency.html). Of course, this is not necessarily intentional: tools such as Sidekiq can use a thread pool or one-off threads for execution of user code.

**Comment by michaelklishin** [comment]
Decreasing concurrency from 20 to 5 still means you have potential concurrency hazards. Try decreasing it to 1 and/or use a mutex around whatever your tasks do with Bunny. That's a good way to verify this particular hypothesis.

As to how Sidekiq tasks can avoid sharing resources such as Bunny channels, I don't know. Presumably each task has an initialization method, you can open a new channel (or even a new connection) there. Obviously Bunny connections are supposed to be long-lived (channels are not necessarily so, by the way), which can be at odds with how Sidekiq operates.

**Comment by olegsobchuk** [comment]
I thought Rabbit support multi-threaded connection, doesn't it?

**Comment by michaelklishin** [comment]
@olegsobchuk what is a multi-threaded connection? Bunny has a separate doc guide on concurrency-related topics. Please consult it. Sharing channels between threads is highly not recommended (this does not apply to Bunny's own consumer work pool). Sharing connections is often fine but if you can afford to not do it, that's not a bad idea.

**Comment by michaelklishin** [comment]
@olegsobchuk your problem is in how Sidekiq's concurrency model and your Sidekiq task code uses Bunny channels. All `Bunny::Channel` methods that expect a server response "memoize" what was the last synchronous protocol operation invoked and when a response arrives, use it. One of the
threads in your case calls a `Bunny::Channel#exchange_declare` (or one of the methods that delegate to it), while another uses `Bunny::Channel#queue_declare` (or one of the methods that delegate to it) concurrently, thus corrupting said channel's internal continuation state.

What RabbitMQ supports or doesn't is irrelevant.
