### ISSUE TITLE
Bunny is not respecting BUNNY_LOG_LEVEL

### ISSUE THREAD

**Issue by luizkowalski** [ruby-amqp/bunny#527]
I have an environment variable as `BUNNY_LOG_LEVEL='info'` and I'm still seeing debug messages
```
D, [2017-11-02T12:10:43.811513 #28] DEBUG -- : Sending a heartbeat, last activity time: 2017-11-02 12:08:46 +0000, interval (s): 0.4
```

I'm actually using sneakers gem to process messages, but Sneakers logger level is already set to INFO and working as expected.

Tracking o Bunny::Session, I found this:
```
log_level        = opts[:log_level] || ENV["BUNNY_LOG_LEVEL"] || Logger::WARN
```
shouldn't maybe `ENV["BUNNY_LOG_LEVEL"]` preced opts[:log_level] since it is global variable? IMO it makes sense to value more env vars before local vars

**Comment by michaelklishin** [comment]
@luizkowalski I disagree.

**Comment by luizkowalski** [comment]
wow...ok...would you mind explain why at least? 😄

**Comment by michaelklishin** [comment]
The reason why options must take precedence over environment variable is this: they are very specific, decided on the case-by-case basis, while environment variables are global by definition. It makes absolutely no sense to make a global value to take precedence over a call site one.

Sneakers may decide to configure Bunny logger however it pleases (although if it defaults to `debug`, that's completely unnecessary). We're not going to change the way Bunny works because of that.

**Comment by luizkowalski** [comment]
I understand...thanks for the explanation
