### ISSUE TITLE
queue.message_count is unstable.

### ISSUE THREAD

**Issue by c2h2** [ruby-amqp/bunny#53]
when queue.subscribe called, sometimes it will report error. and quit.

**Comment by nas** [comment]
We encountered this as well and it happens very often, here is the backtrace if this is what you are after @michaelklishin:

```
Feb 24 10:37:31 routemaster-production app/web.16:  E, [2015-02-24T10:37:30.803556 #6] ERROR -- : app error: undefined method `message_count' for #<AMQ::Protocol::Exchange::DeclareOk:0x007f5a71ce9848> (NoMethodError) 
Feb 24 10:37:31 production app/web.16:  E, [2015-02-24T10:37:30.803684 #6] ERROR -- : /app/vendor/bundle/ruby/2.1.0/gems/bunny-1.6.3/lib/bunny/queue.rb:304:in `status' 
Feb 24 10:37:31 production app/web.16:  E, [2015-02-24T10:37:30.803730 #6] ERROR -- : /app/vendor/bundle/ruby/2.1.0/gems/bunny-1.6.3/lib/bunny/queue.rb:310:in `message_count' 
Feb 24 10:37:31 production app/web.16:  E, [2015-02-24T10:37:30.803767 #6] ERROR -- : /app/config/initializers/00-hirefire.rb:7:in `block (3 levels) in <top (required)>' 
Feb 24 10:37:31 production app/web.16:  E, [2015-02-24T10:37:30.803802 #6] ERROR -- : /app/routemaster/models/subscription.rb:90:in `block in each' 
Feb 24 10:37:31 routemaster-production app/web.16:  E, [2015-02-24T10:37:30.803836 #6] ERROR -- : /app/routemaster/models/subscription.rb:90:in `each' 
Feb 24 10:37:31 production app/web.16:  E, [2015-02-24T10:37:30.803871 #6] ERROR -- : /app/routemaster/models/subscription.rb:90:in `each
```

It works most of the times but at some point it starts breaking with the above error after the server is up for more than 20 hrs or so. If I am not wrong, then in `Bunny::Queue#status` the call `@channel.queue_declare(@name, @options.merge(:passive => true))` should return the object `AMQ::Protocol::Queue::DeclareOk` as this has `message_count` defined.

A common pattern I found is, it happens after a timeout in `Bunny::Concurrent::ContinuationQueue#poll`. Hence, I found  a way of handling it by increasing the timeout or reconnecting in case of a timeout.This has reduced the occurrence but I have also noticed that it happens even without any prior timeout.

**Comment by michaelklishin** [comment]
I suspect that you share a channel between threads.

That's the most likely reason why a continuation for queue.declare stumbles upon exchange.declare-ok.

**Comment by nas** [comment]
We use a `Singleton' class here https://github.com/HouseTrip/routemaster/blob/master/routemaster/models/bunny_channel.rb#L8 when we create the channel. Is there any issue with this?

**Comment by nas** [comment]
@michaelklishin following up on my above reply. Since we are using a single instance of that class application wide once we create the channel, coupled with the fact that we don't have any threading going on and in case of any issues we close the connection and reconnect, hence from that point of view we should only have one channel for the application instance at any point of time (correct me if I am wrong). So there is no chance of sharing the channel in the same application.

On the other hand, we have about 12 - 24 instances of the same application running on different servers depending on the traffic. So I assume these instances should have different channel ids (depending on how AMQP allocates them, haven't gone that far into the code yet), right?

Correct me if I am missing something or if I am wrong anywhere.

**Comment by michaelklishin** [comment]
Channel ids are scoped per connection. Other connections cannot possibly interfere.

I need a test case to reproduce this without (in process) concurrency.
If this was a common issue people would bombard us with reports.

**Comment by michaelklishin** [comment]
@nas the fact that you include the `Singleton` module doesn't make things safe to share between threads. In fact, this may lead to unintentional sharing and have exactly the opposite effect.

You seem to use Unicorn. How sharing may happen with it is less obvious than with Puma but I haven't seen continuations returning a method for a different operations without concurrent channel sharing in a long time.

Consider making your `BunnyChannel` a non-singleton. This certainly goes against the [recommendations in the docs](http://rubybunny.info/articles/concurrency.html).

**Comment by nas** [comment]
@michaelklishin 

> You seem to use Unicorn :smile: 

You are right on that

> sharing may happen with it is less obvious than with Puma ...

IIRC Puma uses threading and forking vs Unicorn only forking. Event if we don't use Puma threading then it will still be same as Unicorn in this case i.e. forking child processes from the master. And we don't want to not do that because that saves us some money considering the number of instances we run.

> Consider making your BunnyChannel a non-singleton

That will be costly as we will be creating channels everytime we construct the object. Considering the amount of messages we publish I think we may get into number of channels issue or some other issue sooner. Hence, this doesn't seem like a viable solution too.

I can only think of two solutions at the moment, since it mainly happens in long running processes:
1.  Create the channel straight after unicorn forks the process to make sure nothing weird is happening while serving requests (though seems very unlikely)  i.e. https://github.com/HouseTrip/routemaster/commit/81f4a87ae8040c00fa41a77ed308006fd977e959
2. Disconnect and recreate the channel after every hour or so.

Still it seems more like a duct tape solution rather than a proper one :(

**Comment by michaelklishin** [comment]
If you insist on having shared state by design, it's your responsibility to synchronise it as needed.

You should connect to external services, including RabbitMQ, from the child process after `fork(2)` happens. Otherwise you are very likely to run into issues with socket sharing and other `fork(2)` idiosyncrasies such as inheriting only 1 thread of the forked process.

**Comment by nas** [comment]
>sets #after_fork hook to a given block. This block will be called by the worker after forking
>
-- <cite>http://unicorn.bogomips.org/Unicorn/Configurator.html</cite>

isn't this https://github.com/HouseTrip/routemaster/commit/81f4a87ae8040c00fa41a77ed308006fd977e959 means it is happening after the forking is done.
