### ISSUE TITLE
ActiveRecord hang in queue.subscribe(block: true)

### ISSUE THREAD

**Issue by Curter29** [ruby-amqp/bunny#543]
I use bunny with rails 5.1.3 and ruby 2.4.3, rabbitmq-server 3.6.15
and code inside daemon proccess (with gem daemon like Daemons.run("script.rb"))

script.rb => 
```ruby
  conn = Bunny.new
  conn.start
  ch = conn.create_channel
  queue_name = :sample
  exchange_name = "#{queue_name}_"
  q = ch.queue(queue_name, auto_delete: false, durable: true)
  x = ch.exchange(exchange_name, type: "fanout")
  q.bind(x)

  q.subscribe(manual_ack: true, block: true) do |delivery_info, properties, params|
    # income message - works
    # but when i try any ActiveRecord - all freezed here
    ActiveRecord::Base.connection.reconnect!
    ap User.last
    ch.ack(delivery_info.delivery_tag)
  end  
```
then i send message to queue, when message come in subscribe, all fine, but if i try use any ActiveRecord query, code stop working at all (juts freeeze) without any errors

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Bunny is entirely unaware of ActiveRecord and does not share anything with it. Produce a [thread dump](http://www.mikeperham.com/2012/06/02/debugging-with-thread-dumps/) or [use gdb](https://blog.newrelic.com/2013/04/29/debugging-stuck-ruby-processes-what-to-do-before-you-kill-9/) to find out what's going on.

Reconnecting for each delivery is probably unnecessary and increases the risk of slow or stuck connections, so consider avoiding that.

**Comment by clive-hetzner** [comment]
@Curter29 Was it just happening for you with ActiveRecord? I'm finding the same behaviour with any subscribe where I use block: true, no actual code get's executed within the those blocks until I break out or kill the process, at which point a flood of execution for all messages that were taken off the queue suddenly get processed.

**Comment by michaelklishin** [comment]
This is not a support or discussion forum.

`Bunny::Queue#subscribe(block: true)` was a terrible mistake. It was only added to make certain tutorial quality code easy to run since without the "blocking" aspect the smallest consumer example would just naturally terminate.

**DO NOT use `block: true` for anything** other than tutorial code. In any Web application, there's already a bunch of long-running threads that prevent the VM from exiting and the option has absolutely no effect on how consumers behave expect that the `subscribe` method pwould return only after all channel work pool threads are done](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/queue.rb#L195) (when the channel is closed).

I will remove the option from the docs everywhere since explaining this over and over is getting old.

**Comment by clive-hetzner** [comment]
@Curter29 or use a different library, it seems @michaelklishin has somewhat of an attitude problem so you'll probably find other bugs he doesn't want to explain littered through the code.

**Comment by michaelklishin** [comment]
One very common reason for "not receiving any deliveries unless the app is killed" is a channel exception. See server logs for confirmations of this hypothesis.

Another is connection recovery that's not enabled or a connection that has trouble recovering (it will produce quite a bit of log noise these days).

**Comment by michaelklishin** [comment]
@clive-hetzner I'm sorry if my attitude offends you. I explain what this "bug" is and just provided a few more suggestions on what might be going on since a couple of sentences is all the information there is to work here.

I've put hundreds of hours into Bunny and its docs, all of which havee been available to anyone who wants it for free, for about 9 years now, with ongoing updates and support. I expect that those who use my work for free appreciate it at least a little bit and instead of insulting me either contribute (not necessarily code, just relevant information *only you* have such as thread dumps) or don't expect a 5 star hotel concierge kind of response to a 2 line "bug report".

**Comment by clive-hetzner** [comment]
@michaelklishin this is not a discussion forum.

Initiating conversation with you was a terrible mistake. It was only started to gain more information, to improve the quality of an eventual submitted fuller bug report.

**DO NOT bother responding**

I will remove this, broken, library from our code-base as it does more harm than good.

**Comment by michaelklishin** [comment]
@clive-hetzner wow, talk about having an attitude problem.

You are using a "feature" that unlikely to be the root cause (even though it is problematic as I admitted first hand), was never meant to be used in production, provided no details and ignored all [README guidelines on getting help](https://github.com/ruby-amqp/bunny#community-and-getting-help), ignored all the specific advice you were given, and now jumping to conclusions about the quality of this library.

Ever wondered why so many open source maintainers burn out and quit? Maybe it's because they are supposed to give their work away for free, do support for free on top of that and get 0 appreciation in return? 🤔

**Comment by michaelklishin** [comment]
A number of comments that contributed exactly nothing (including my own) to this issue have been removed.

First of all, `block: true` only was meant to be used in tutorials. It doesn't change how deliveries are processed by Bunny but does block the calling thread until all of the channel's work pool threads are released (which usually happens only when the channel is closed). I doubt it is the root cause here but it makes reasoning about the code harder and is not really necessary.

Bunny dispatches certain consumer operations (such as deliveries) to a thread pool. The pool has the size of 1 by default to avoid surprising race conditions. `Bunny::Session#create_channel` makes it possible to provide pool size as the 3rd argument.

If something in the consumer (`subscribe` blocks count as consumers) blocks the thread, future deliveries won't be dispatched. In applications where this is a possibility it may be a good idea to perform such operations on a different thread/event loop/etc — that is, no on the Bunny's work pool thread). Enabling debug logging for Bunny connection(s) will help identify such issues as every inbound frame will be logged.

Another possible scenario is that the channel was closed. No deliveries or other activity is possible on a closed channel. Server logs is the best way to spot channel exceptions. We don't have any evidence of channel exceptions here.

**Comment by michaelklishin** [comment]
I tried to reproduce with the following `Gemfile`:

``` ruby
source "https://rubygems.org"

gem "bunny"
gem "activerecord"
gem "pg"
```

and script:

``` ruby
require "bundler"
Bundler.setup

require "bunny"
require "active_record"

ActiveRecord::Base.establish_connection({
  host: 'localhost',
  adapter: 'postgresql',
  encoding: 'utf-8',
  database: 'test'
})

c  = Bunny.new; c.start
ch = c.create_channel

ch.queue("bunny.issues.543", durable: false).subscribe(manual_ack: true, block: true) do |delivery_info, properties, payload|
  puts "Consumed a delivery"
  puts ActiveRecord::Base.connection.reconnect!
  ch.ack(delivery_info.delivery_tag)
end
```

or this variation without `block: true`:

``` ruby
```

They both produce the same expected outcome: a successful PostgreSQL connection, a message to the standard output and a consume that makes progress (future deliveries are dispatched).

So there is no obvious problematic interplay (as expected) between Bunny and ActiveRecord or the PostgreSQL client's concurrency models. Chances are it's one of the scenarios explained above.

**Comment by michaelklishin** [comment]
I'm going to update the Queues and Consumers guide to cover some of the concerns listed above. Any future questions on the topic are welcome on both Bunny's own and RabbitMQ mailing lists.
