### ISSUE TITLE
SOCKS5 Sockets?

### ISSUE THREAD

**Issue by esiegel** [ruby-amqp/bunny#571]
Is there a way to control socket creation/modification.  I need to connect to a Rabbitmq broker that only permits whitelisted IPs.  Currently, I can't assign static IPs to my clients and am considering using proxies before attempting something more drastic like changing infrastructure. 

Currently using 2.8.0, but I believe this applies to all versions.  I see in my my version of bunny, that there is a `socket_configurator`, which I don't think would help in this exact situation, but is on the right track.

I guess the other option is always monkey patching.

Any help or advice is much appreciated.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The purpose of the socket configurator is to allow arbitrary code to be applied to the socket before `Bunny::Session#start` is called and initiates the connection.

It's much more common to use a "transparent" TCP proxy in front of RabbitMQ, such as HAproxy. There is a Ruby project that claims to [redirect any TCP sockets](https://github.com/astro/socksify-ruby) via a proxy. I have never tried it.

**Comment by michaelklishin** [comment]
Note that the library mentined above seems to be GPL3-licensed. Commit history claims the Ruby license was added but it is not clearly advertised. I'd double check what's the licensing status is before seriously considering it.

**Comment by esiegel** [comment]
Thank you for the quick response and apologies for not first seeking help in the Google Group.  I guess in my mind I was thinking of this as a potential Feature Request, though HAProxy or that library you referenced will probably work fine.

**Comment by michaelklishin** [comment]
HAproxy is a very popular option that gives you a lot of operational features that many SOCKS5 proxies won't (rate limiting, [Proxy protocol](http://www.rabbitmq.com/networking.html#proxy-protocol) support) and more. Perhaps, more importantly, it has *a lot* of information about it in the docs and various online forums. So I think we shouldn't address this feature request as there is a better option already ;)
