### ISSUE TITLE
Channel.reject not working immediately

### ISSUE THREAD

**Issue by juliofalbo** [ruby-amqp/bunny#602]
Hi all.

My scenario is:

I have a consumer that is configured to have a manual ack.

This consumer is responsible to get the message and communicate with a third-party app, and if this third party is not available I would like to reject the message and requeue.

So, basically in code I'm doing this:

```
@subscriptions = {}

def subscribe(channel)
    subscription = channel.queue('my.queue', { durable: true }).subscribe(manual_ack: true) do |delivery_info, metadata, 
    payload|
          callback(channel, delivery_info, metadata, payload)
    end
    @subscriptions['my.queue'] = subscription
end

def callback(channel, delivery_info, metadata, payload)
    # Checking if my third party is down and it is
    subscription = @subscriptions['my.queue']
    subscription.cancel
    channel.reject(delivery_info.delivery_tag, true)
    # Try to reconnect with the third-part app - Timeout 5min
end
```

The bugs are:
1 - When I'm executing the line `channel.reject(delivery_info.delivery_tag, true)` the message is still in the `Unacked` state on RabbitMQ, it means that any other consumers can't get it.

I need to wait for the entire method execution to, in fact, release the message. It means that I need to wait in the worst case, 5 minutes.

2 - The operation `subscription.cancel` it is taking 1 minute

**Comment by michaelklishin** [comment]
Please post your questions to the mailing list.

A traffic capture would be able to confirm but your code seems to be blocking the consumer dispatch loop. 60 seconds is the default [peer unavailability detection timeout](https://www.rabbitmq.com/heartbeats.html). Consumer deliveries are dispatched to a thread pool which only has a single thread (to eliminate any unexpected concurrency hazards) by default.
That's my best guess anyway, server logs, Bunny debug logs and a traffic capture will eliminate any need to guess what is going on.

A much better approach with long-running actions would be to hand over this task to a thread pool of your own, or maybe even a one-off thread if the rate isn't going to be high. A block passed to it should capture the channel reference since you can only acknowledge or re-queue on the same channel the delivery was on. You also have to keep in mind that the channel may be closed by then. This means the delivered message was [automatically requeued](https://www.rabbitmq.com/confirms.html) and will be delivered, to this consumer or another instance.
